import os
import sys
import time
import csv
import requests
import logging
import apprise
from datetime import datetime, timedelta, timezone
from dotenv import load_dotenv
from seleniumbase import Driver
from selenium.webdriver.common.by import By

# --- Logging Configuration ---
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)
logger = logging.getLogger(__name__)

# Load configuration from .env file
load_dotenv()

NIGHTSCOUT_URL = os.getenv("NIGHTSCOUT_URL", "").rstrip("/")
NIGHTSCOUT_TOKEN = os.getenv("NIGHTSCOUT_API_TOKEN")
PAST_DAYS = int(os.getenv("PAST_DAYS", 30))
GENERATED_BY = os.getenv("GENERATOR_NAME", "Unknown")
SERIAL_NUMBER = os.getenv("LIBRE_SERIAL_NUMBER", "00000000-0000-0000-0000-000000000000")

GLOOKO_EMAIL = os.getenv("GLOOKO_EMAIL")
GLOOKO_PASSWORD = os.getenv("GLOOKO_PASSWORD")
HEADLESS = os.getenv("HEADLESS_BROWSER", "True").lower() == "true"
APPRISE_URL = os.getenv("APPRISE_URL")

OUTPUT_FILE = "nightscout_history.csv"

def send_notification(title, body):
    """Sends a notification if APPRISE_URL is configured."""
    if not APPRISE_URL:
        return
    
    try:
        apobj = apprise.Apprise()
        apobj.add(APPRISE_URL)
        apobj.notify(title=title, body=body)
        logger.info("Sent failure notification via Apprise.")
    except Exception as e:
        logger.error(f"Failed to send Apprise notification: {e}")

def check_nightscout_units():
    logger.info(f"Checking Nightscout configuration at {NIGHTSCOUT_URL}...")
    try:
        response = requests.get(f"{NIGHTSCOUT_URL}/api/v1/status.json", params={"token": NIGHTSCOUT_TOKEN})
        response.raise_for_status()
        units = response.json().get("settings", {}).get("units", "")
        
        if "mmol" not in units.lower():
            logger.error(f"Nightscout is configured to use '{units}', not 'mmol/L'. Currently only mmol/L is supported.")
            sys.exit(1)
    except requests.exceptions.RequestException as e:
        logger.error(f"Failed to fetch status from Nightscout. Error: {e}")
        send_notification("GlookoScout Error", f"Failed to fetch status from Nightscout: {e}")
        sys.exit(1)

def fetch_nightscout_data():
    logger.info(f"Fetching glucose records for the past {PAST_DAYS} days...")
    
    start_date = datetime.now(timezone.utc) - timedelta(days=PAST_DAYS)
    start_timestamp_ms = int(start_date.timestamp() * 1000)
    
    params = {
        "token": NIGHTSCOUT_TOKEN,
        "find[date][$gte]": start_timestamp_ms,
        "count": 100000 
    }
    
    response = requests.get(f"{NIGHTSCOUT_URL}/api/v1/entries.json", params=params)
    if response.status_code != 200:
        logger.error(f"Failed to fetch data. HTTP {response.status_code}")
        send_notification("GlookoScout Error", f"Failed to fetch Nightscout data. HTTP {response.status_code}")
        sys.exit(1)
        
    data = response.json()
    if not data:
        logger.warning("No data found in Nightscout for the specified timeframe.")
        sys.exit(1)

    data.sort(key=lambda x: x.get("date", 0))
    generated_on = datetime.now(timezone.utc).strftime("%d-%m-%Y %H:%M UTC")

    col_headers = [
        "Device", "Serial Number", "Device Timestamp", "Record Type", 
        "Historic Glucose mmol/L", "Scan Glucose mmol/L", "Non-numeric Rapid-Acting Insulin", 
        "Rapid-Acting Insulin (units)", "Non-numeric Food", "Carbohydrates (grams)", 
        "Carbohydrates (servings)", "Non-numeric Long-Acting Insulin", 
        "Long-Acting Insulin Value (units)", "Notes", "Strip Glucose mmol/L", 
        "Ketone mmol/L", "Meal Insulin (units)", "Correction Insulin (units)", 
        "User Change Insulin (units)"
    ]

    with open(OUTPUT_FILE, mode='w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f, delimiter=',') 
        writer.writerow(["Glucose Data", "Generated on", generated_on, "Generated by", GENERATED_BY])
        writer.writerow(col_headers)

        for entry in data:
            if entry.get("type") != "sgv" or not entry.get("date") or not entry.get("sgv"):
                continue 
            
            dt = datetime.fromtimestamp(entry.get("date") / 1000.0)
            timestamp_str = dt.strftime("%d-%m-%Y %H:%M") 
            sgv_mmol = round(entry.get("sgv") / 18.0182, 1)

            device = entry.get("device", "FreeStyle LibreLink")
            if not device or device.lower() == "unknown":
                device = "FreeStyle LibreLink"
            
            row = [
                device, SERIAL_NUMBER, timestamp_str, "0", str(sgv_mmol), 
                "", "", "", "", "", "", "", "", "", "", "", "", "", "" 
            ]
            writer.writerow(row)
            
    logger.info(f"Successfully wrote {len(data)} records to {OUTPUT_FILE}")

def upload_to_glooko():
    absolute_file_path = os.path.abspath(OUTPUT_FILE)
    logger.info("Launching stealth browser for Glooko upload...")
    
    driver = Driver(uc=True, headless=HEADLESS) 
    
    try:
        driver.get("https://my.glooko.com/users/sign_in")
        time.sleep(3) 
        
        try:
            driver.click("#onetrust-reject-all-handler", timeout=5)
            time.sleep(1) 
        except Exception:
            pass

        logger.info("Logging in...")
        driver.type("#user_email", GLOOKO_EMAIL)
        driver.type("#user_password", GLOOKO_PASSWORD)
        driver.click("#sign-in-button")
        
        driver.wait_for_element_visible("button.AbbottCSVButton_abbottCsvUpload", timeout=15)
        logger.info("Login successful. Initiating LibreView Upload...")
        
        driver.click("button.AbbottCSVButton_abbottCsvUpload")
        driver.wait_for_element_visible('[data-testid="button-file-uploader-upload"]', timeout=5)
        
        file_input = driver.find_element(By.CSS_SELECTOR, "input[type='file']")
        file_input.send_keys(absolute_file_path)

        driver.wait_for_element_visible('[data-testid="button-file-uploader-confirm"]', timeout=5)
        driver.click('[data-testid="button-file-uploader-confirm"]')

        logger.info("Waiting for upload to process...")
        driver.wait_for_element_visible(
            '[data-testid="dialog-file-uploader-success"], [data-testid="dialog-file-uploader-failed"]', 
            timeout=60
        )

        if driver.is_element_visible('[data-testid="dialog-file-uploader-success"]'):
            logger.info("UPLOAD SUCCESSFUL!")
            driver.click('[data-testid="button-file-uploader-success-done"]')
            time.sleep(2)
        elif driver.is_element_visible('[data-testid="dialog-file-uploader-failed"]'):
            logger.error("UPLOAD FAILED: Glooko rejected the file.")
            send_notification("GlookoScout Upload Failed", "Glooko rejected the uploaded CSV file.")
            driver.click('[data-testid="button-file-uploader-failed-upload-error-close"]')
            time.sleep(2)

    except Exception as e:
        logger.error(f"An error occurred during upload: {e}")
        send_notification("GlookoScout Upload Error", f"An exception occurred during browser automation, if this persists, open a github issue:\n{e}")
    finally:
        try:
            driver.quit()
        except:
            pass
        try:
            if os.path.exists(absolute_file_path):
                os.remove(absolute_file_path)
                logger.info(f"Cleaned up: Deleted {OUTPUT_FILE}")
        except OSError as e:
            logger.warning(f"Could not delete {OUTPUT_FILE}. Error: {e}")

def main():
    if not NIGHTSCOUT_URL or not GLOOKO_EMAIL:
        logger.error("Missing required environment variables. Please check your .env file.")
        sys.exit(1)
        
    check_nightscout_units()
    fetch_nightscout_data()
    upload_to_glooko()

if __name__ == "__main__":
    main()